FROM python:3.11-slim

WORKDIR /app

# Устанавливаем системные зависимости, включая cron
RUN apt-get update && apt-get install -y \
    gdal-bin \
    libgdal-dev \
    binutils \
    libproj-dev \
    build-essential \
    cron \
    && rm -rf /var/lib/apt/lists/*

COPY ../requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY ../ .

# Копируем cron-файл в систему
COPY docker/crontab /etc/cron.d/refresh-cron

# Делаем его исполняемым и активируем
RUN chmod 0644 /etc/cron.d/refresh-cron && \
    crontab /etc/cron.d/refresh-cron

# Лог файл для cron
RUN touch /var/log/cron.log

# Разрешаем запуск скрипта
RUN chmod +x ./docker/start_back.sh

ENV GDAL_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu/libgdal.so

# Запускаем и cron, и Django
CMD ["sh", "-c", "cron && ./docker/start_back.sh"]
