FROM python:3.11-slim

WORKDIR /app

# Устанавливаем системные зависимости, включая GDAL и заголовочные файлы для сборки
RUN apt-get update && apt-get install -y \
    gdal-bin \
    libgdal-dev \
    binutils \
    libproj-dev \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

# Копируем requirements.txt (предполагается, что он в корне build context)
COPY ../requirements.txt .

# Устанавливаем python-зависимости
RUN pip install --no-cache-dir -r requirements.txt

# Копируем остальной проект в контейнер
COPY ../ .

# Делаем скрипт запуска исполняемым
RUN chmod +x ./docker/start_back.sh

# Если нужно, задаем переменную окружения GDAL_LIBRARY_PATH (обычно так не обязательно, но бывает)
ENV GDAL_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu/libgdal.so

# Команда запуска (можно заменить на свою)
CMD ["./docker/start_back.sh"]
